import type {Buyer,Crop,FarmerProfile,FpoLot,Grievance,MarketOption,MarketPrice,Offer,Sale} from '@/types';
export const demoFarmer:FarmerProfile={name:'Ramesh Patil',location:'Nashik, Maharashtra',farmSizeAcres:4.5,phone:'+91 98765 43210',memberSince:'Jan 2026'};
export const demoCrops:Crop[]=[{id:'crop-1',name:'Wheat',quantityKg:2000,location:'Nashik, Maharashtra',quality:'Grade A',harvestDate:'2026-08-20',expectedSellingDate:'2026-09-12',storageAvailable:true,createdAt:Date.now()-86400000*3},{id:'crop-2',name:'Onion',quantityKg:1500,location:'Nashik, Maharashtra',quality:'Grade B',harvestDate:'2026-08-28',expectedSellingDate:'2026-09-10',storageAvailable:false,createdAt:Date.now()-86400000}];
export const demoMarketOptions:Record<string,MarketOption[]>={Wheat:[{id:'mkt-a',name:'Lasalgaon APMC Mandi',type:'Market',pricePerKg:34,transportCost:6000,storageCost:1500,handlingCost:800,otherCost:200,distanceKm:85,location:'Lasalgaon, Maharashtra',pickupAvailable:false,verified:true},{id:'mkt-b',name:'Nashik Local Market',type:'Market',pricePerKg:32,transportCost:800,storageCost:600,handlingCost:400,otherCost:200,distanceKm:12,location:'Nashik, Maharashtra',pickupAvailable:false,verified:true},{id:'buyer-c',name:'Shree Agro Industries',type:'Verified Buyer',pricePerKg:31.5,transportCost:0,storageCost:0,handlingCost:500,otherCost:500,distanceKm:18,location:'Nashik, Maharashtra',pickupAvailable:true,verified:true}],Onion:[{id:'onion-mkt-a',name:'Lasalgaon Onion Mandi',type:'Market',pricePerKg:22,transportCost:4000,storageCost:1000,handlingCost:500,otherCost:200,distanceKm:85,location:'Lasalgaon, Maharashtra',pickupAvailable:false,verified:true},{id:'onion-mkt-b',name:'Nashik Local Market',type:'Market',pricePerKg:20,transportCost:600,storageCost:400,handlingCost:300,otherCost:100,distanceKm:12,location:'Nashik, Maharashtra',pickupAvailable:false,verified:true},{id:'onion-buyer-c',name:'Fresh Foods Pvt Ltd',type:'Verified Buyer',pricePerKg:19.5,transportCost:0,storageCost:0,handlingCost:400,otherCost:300,distanceKm:22,location:'Nashik, Maharashtra',pickupAvailable:true,verified:true}]};
export const demoBuyers:Buyer[]=[{id:'buyer-1',name:'Shree Agro Industries',requiredCrop:'Wheat',requiredQuantityKg:5000,offeredPricePerKg:31.5,location:'Nashik, Maharashtra',pickupAvailable:true,verified:true,rating:4.7},{id:'buyer-2',name:'Maharashtra Flour Mills',requiredCrop:'Wheat',requiredQuantityKg:3000,offeredPricePerKg:30,location:'Pune, Maharashtra',pickupAvailable:true,verified:true,rating:4.5},{id:'buyer-3',name:'Fresh Foods Pvt Ltd',requiredCrop:'Onion',requiredQuantityKg:2000,offeredPricePerKg:19.5,location:'Nashik, Maharashtra',pickupAvailable:true,verified:true,rating:4.8},{id:'buyer-4',name:'Spice Route Exporters',requiredCrop:'Onion',requiredQuantityKg:10000,offeredPricePerKg:21,location:'Mumbai, Maharashtra',pickupAvailable:false,verified:true,rating:4.3},{id:'buyer-5',name:'Bharat Grain Traders',requiredCrop:'Wheat',requiredQuantityKg:2000,offeredPricePerKg:29.5,location:'Dhule, Maharashtra',pickupAvailable:false,verified:false,rating:3.9}];
export const demoOffers:Offer[]=[{id:'offer-1',buyerId:'buyer-1',buyerName:'Shree Agro Industries',cropId:'crop-1',cropName:'Wheat',quantityKg:2000,offeredPricePerKg:31.5,transportCost:0,storageCost:0,handlingCost:500,otherCost:500,status:'pending',createdAt:Date.now()-18000000},{id:'offer-2',buyerId:'buyer-2',buyerName:'Maharashtra Flour Mills',cropId:'crop-1',cropName:'Wheat',quantityKg:2000,offeredPricePerKg:30,transportCost:1500,storageCost:0,handlingCost:600,otherCost:400,status:'pending',createdAt:Date.now()-43200000}];
export const demoSales:Sale[]=[{id:'sale-1',cropName:'Soybean',buyerName:'Shree Agro Industries',quantityKg:1200,netReturn:38400,currentStage:'pickup_scheduled',stages:['crop_listed','buyer_selected','pickup_scheduled'],createdAt:Date.now()-86400000*5}];
export const demoGrievances:Grievance[]=[];
function trend(base:number){return Array.from({length:8},(_,i)=>({date:new Date(Date.now()-(7-i)*86400000).toISOString().slice(0,10),price:Math.round((base+Math.sin(i*1.3)*1.5)*100)/100}))}
export const demoMarketPrices:MarketPrice[]=[{crop:'Wheat',market:'Lasalgaon APMC',currentPrice:34,previousPrice:33.5,unit:'₹/kg',trend:'up',trendHistory:trend(34)},{crop:'Wheat',market:'Nashik Local',currentPrice:32,previousPrice:32,unit:'₹/kg',trend:'stable',trendHistory:trend(32)},{crop:'Onion',market:'Lasalgaon Mandi',currentPrice:22,previousPrice:24,unit:'₹/kg',trend:'down',trendHistory:trend(22)},{crop:'Onion',market:'Nashik Local',currentPrice:20,previousPrice:19,unit:'₹/kg',trend:'up',trendHistory:trend(20)}];
export const demoFpoLots:FpoLot[]=[{id:'fpo-1',cropName:'Wheat',totalQuantityKg:12000,farmerCount:6,location:'Nashik, Maharashtra',askingPricePerKg:33,status:'open'},{id:'fpo-2',cropName:'Onion',totalQuantityKg:8500,farmerCount:4,location:'Nashik, Maharashtra',askingPricePerKg:21,status:'open'},{id:'fpo-3',cropName:'Soybean',totalQuantityKg:5000,farmerCount:3,location:'Pune, Maharashtra',askingPricePerKg:44,status:'matched'}];
export const demoImpactMetrics={marketOptionsCompared:18,buyerConnections:7,offersReceived:5,transactionsTracked:3,totalFarmers:1240,totalCropValue:8450000};
